name: CI/CD for Codenames

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          set -e
          cd ~/codenames

          git reset --hard HEAD
          git pull origin main

          echo "Rebuilding containers"
          docker compose -f docker-compose.prod.yml down --remove-orphans
          docker compose -f docker-compose.prod.yml up -d --build

          echo "Waiting for containers to be healthy..."
          for service in mysql redis web; do
            container_id=$(docker compose -f docker-compose.prod.yml ps -q $service)
            echo "Waiting for $service..."

            timeout 120s bash -c "
              until [ \"\$(docker inspect -f '{{.State.Health.Status}}' $container_id 2>/dev/null)\" = 'healthy' ]; do
                sleep 5
              done
            " || {
              echo "$service did not become healthy in time!"
              docker logs $container_id
              exit 1
            }

            echo "$service is healthy."
          done

          echo "Running Django commands..."
          docker compose -f docker-compose.prod.yml exec -T web bash -c "
            python manage.py check --deploy &&
            python manage.py makemigrations --no-input &&
            python manage.py migrate --no-input &&
            python manage.py collectstatic --no-input --clear
          "

          echo "Deployment successful!"